apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: motiontracker-db
  labels:
    app.kubernetes.io/part-of: motiontracker
spec:
  instances: 1
  storage:
    size: 10Gi
    storageClass: synostoragev2
  enableSuperuserAccess: false
  bootstrap:
    initdb:
      database: motiontracker
      owner: motiontracker
      secret:
        name: motiontracker-db-credentials
  monitoring:
    enablePodMonitor: false
