---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: motiontracker-db-credentials
  namespace: default
spec:
  encryptedData:
    password: AgCV8AL3w0P4NK+RZWJwa60ozeggCUL/scYubxAuviC8K8Dsp0G63bFohT9Cr+/SEt77MFtze8uXMlPrZNnG8rEiQw6m73NdrYL3BMJlT1qtuW0IAILxcYTm0LlzZaS2GXRfhVzSfRwvMCrzlEvQyl1MvU/ixjJsMZRWJrZazgHSlb2xoHax60UCvLbUUegkanXLxpKoV/25WYPD3+Npnj4HiOm55kRnlKRZdG7g6Yr4AQXBdDHGg3F7I19/lvdZyAgVmJhBjfYdmM91uvqf1fVAvwmgUWGUZi1z5gRQmSRBHiXkAMSNIHo0S8UljO9vu+pZBwd63vqAUnuz2ctIiuRtAk29OeQBIWapEQN2LvKsIY9dBlTfamp5pvyD3RfomLH08qBG1B8wjq9JESNEtF0/4qgDoTOiWOqRu+oBr6IOE005JFEZpUjjOF6KU0aFr4V31BT7JzhFZSJKKENIpI3pTT/f9Y6DoZf+sNoq38alojIHCK10KNSkU59nxj9K/Fenyy9fOevdALxAJfX9AEjCQN5TTn9VGubMBE0pMOIn6eqzn9Ps1uK0pn5Mq5mvvR5YA4MBpEo5BeBrCc9U+TwanpPN/zknRhzWaFUO5L3I0/NKQb8YFQG/s3bb5XhQ6L91MekNyK3iuWPsroqV53mQmbtu/K9vAFI4cBATrQkzqUgTg5YRZxRmRYTiUCcrmPBY0TxZwnir/dgJJ/d6g6NNDM//yw==
    username: AgC41ATrBiNwG5pkK1CNfGj1VmB4kx1qs1i1d3z1l0uyVOmyRazx7SUR9A19/hBAihZxRnTPEuE/u1zf0cNi/bXcAIaUIQFlJwIuRx33nMHuXhjyD6TNse6R9WcjngzNjQA3rHjmMbOD1dMvwn08UI0NQlGacUl74ifJb9q8nCOF4U6HWgacTlOauSbVrGKynq0fa9GBxBtRDaYNlWBLBuKi0dxwxZ2bpnT4LSV039AmC6qVrlGeY13zZ4Pwvz09XCfgtPZd0AvL3GFos75pJXWIynyn/W1kNFBGUiaetEWRw2VqKS9dgrDAVIm1o3Ih1KbR72pT9wvSpMlc0d7OTr+uRx5XnJI7YLPd2KeNy+114LhHjkRiDohnwYYz6YF9Uxe6enIPWEEjX0qSogYwyxFuYb4TUgrLfsmPtCDLtXxuBtsVYVE2Fi5Lbd8zrmf/esEa8lNvu6Qv41ctxOCF1mLCedkkKR+kHp9XVx6HAvqh3w+rVYlSY1P1GGzFNElJF9heUJ3mltreGNDh0QWQ4XWDYSGxm5RuXtAXVY/LzDmR3g8XPVPQd4O9fiar+zMOF7RLZRT+JpEWxmmTEwAfG1V7rcnKSix+c4rnunkhsH500SETWxEFasgrS5qdxNXgPTWzYL+OdLpXWeZhtoux7I8RAPeiTF5JRD8ctPBfx6DaODG5JLAlms6ArY6ce12XcXEtAJH5HdJZPGczcRUE
  template:
    metadata:
      labels:
        app.kubernetes.io/part-of: motiontracker
      name: motiontracker-db-credentials
      namespace: default
    type: kubernetes.io/basic-auth
